# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-01 08:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsLetter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newsletter', models.TextField(blank=True, null=True)),
                ('details', models.TextField(blank=True, null=True, verbose_name='Details')),
            ],
        ),
        migrations.CreateModel(
            name='PhotoGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images%Y/%m/%d')),
                ('event_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Event Name')),
                ('hits', models.IntegerField(blank=True, null=True)),
                ('comments', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True, verbose_name='Discription')),
            ],
        ),
        migrations.CreateModel(
            name='SuccessStories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images%Y/%m/%d')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Title')),
                ('authur', models.CharField(blank=True, max_length=255, null=True, verbose_name='Authur')),
                ('story', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
