# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-01 10:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia', '0002_newsletter_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsletter',
            name='details',
        ),
        migrations.RemoveField(
            model_name='newsletter',
            name='newsletter',
        ),
        migrations.AddField(
            model_name='newsletter',
            name='body',
            field=models.TextField(blank=True, null=True, verbose_name='Body'),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Title'),
        ),
    ]
