# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-02 11:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia', '0003_auto_20170901_1013'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsletter',
            options={'ordering': ['-created'], 'verbose_name': 'NEWS LETTER', 'verbose_name_plural': 'NEWS LETTER'},
        ),
        migrations.AlterModelOptions(
            name='photogallery',
            options={'ordering': ['-created']},
        ),
        migrations.AlterModelOptions(
            name='successstories',
            options={'ordering': ['-created'], 'verbose_name': 'SUCCESS STORY', 'verbose_name_plural': 'SUCCESS STORIES'},
        ),
        migrations.AddField(
            model_name='photogallery',
            name='created',
            field=models.DateTimeField(auto_now=True, verbose_name='Created'),
        ),
        migrations.AddField(
            model_name='successstories',
            name='created',
            field=models.DateTimeField(auto_now=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='created',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now, verbose_name='Created'),
            preserve_default=False,
        ),
    ]
