# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-06 13:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='careers',
            options={'ordering': ['-created'], 'verbose_name': 'CAREER', 'verbose_name_plural': 'CHAREERS'},
        ),
        migrations.AlterModelOptions(
            name='chairpersonsremarks',
            options={'ordering': ['-created'], 'verbose_name': "CHAIRPERSON'S REMARK", 'verbose_name_plural': "CHAIRPERSON'S REMARKS"},
        ),
        migrations.AlterModelOptions(
            name='contactus',
            options={'ordering': ['-created'], 'verbose_name': 'CONTACT US', 'verbose_name_plural': 'CONTACT US'},
        ),
        migrations.AlterModelOptions(
            name='ourmainobjective',
            options={'ordering': ['-created'], 'verbose_name': 'OUR MAIN OBJECTIVE', 'verbose_name_plural': 'OUR MAIN OBJECTIVES'},
        ),
        migrations.AlterModelOptions(
            name='ourteam',
            options={'ordering': ['-created'], 'verbose_name': 'OUR TEAM', 'verbose_name_plural': 'OUR TEAMS'},
        ),
        migrations.AlterModelOptions(
            name='ourvision',
            options={'ordering': ['-created'], 'verbose_name': 'OUR VISION', 'verbose_name_plural': 'OUR VISIONS'},
        ),
        migrations.AlterModelOptions(
            name='whoweare',
            options={'ordering': ['-created'], 'verbose_name': 'WHO WE ARE', 'verbose_name_plural': 'WHO WE ARE'},
        ),
    ]
