# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-08 10:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0002_auto_20170906_1334'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'ordering': ['-created'], 'verbose_name': 'CONTACT FORM', 'verbose_name_plural': 'CONTACT FORMS'},
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='contact',
        ),
        migrations.AddField(
            model_name='contactus',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='contactus',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Full Name'),
        ),
        migrations.AddField(
            model_name='contactus',
            name='message',
            field=models.TextField(blank=True, null=True, verbose_name='Message'),
        ),
    ]
