# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-01 03:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Graphs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Graph_title')),
                ('year', models.DateField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created'],
                'verbose_name': 'GRAPH',
                'verbose_name_plural': 'GRAPHS',
            },
        ),
        migrations.CreateModel(
            name='Resources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_name', models.CharField(max_length=255, verbose_name='Resource_name')),
                ('resource_link', models.TextField(verbose_name='Resource_link')),
                ('resource_type', models.CharField(max_length=255, verbose_name='Resource_type')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created'],
                'verbose_name': 'RESOURCE',
                'verbose_name_plural': 'RESOURCES',
            },
        ),
    ]
