# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-01 03:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='graphs',
            name='link',
            field=models.TextField(null=True, verbose_name='graph_link'),
        ),
    ]
