# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-01 10:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FrequentlyAskQuestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(blank=True, max_length=255, null=True, verbose_name='Question')),
                ('answer', models.CharField(blank=True, max_length=255, null=True, verbose_name='Answer')),
            ],
        ),
    ]
