# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-01 10:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0002_frequentlyaskquestions_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frequentlyaskquestions',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created'),
        ),
    ]
